apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-green
  labels:
    app: helloworld-green
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%  
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: helloworld
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: TARGET
          value: "version2"
